#!/usr/bin/env bash

if (( $# > 1 ));then
    norminette "$@"
    gcc -Wall -Wextra -Werror "$@"
else
    #引数なしで分割コンパイル、./a.outを生成する
    echo "##########norminette##########"
    norminette
    echo "##########分割コンパイル##########"
    gcc -c -Wall -Wextra -Werror $(find . -name '*.c')
    echo "##########リンク##########"
    gcc -Wall -Wextra -Werror $(find . -name '*.o')
    rm -f ./*.o
fi
echo "##########実行5,3##########"
./a.out 5 3
echo "##########実行5,1##########"
./a.out 5 1
echo "##########実行1,1##########"
./a.out 1 1
echo "##########実行1,5##########"
./a.out 1 5
echo "##########実行4,4##########"
./a.out 4 4
echo "##########実行10,10##########"
./a.out 10 10 #
echo "##########終了##########"
rm -f a.out
